# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     container_name: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: 968498912Gu.
#       MYSQL_DATABASE: courses

#   app:
#     build: .
#     container_name: spring-backend
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgress://db:3306/courses
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: 968498912Gu.
#     depends_on:
#       - db


services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
